# =========================================================
# src/company_rules_prompt.py
# Company STP/NSTP rules embedded for prompt-based rule checking
#
# Generated from rules_master_clean.csv.
# Important: these rules are NOT retrieved from SQL or vector DB.
# The agent injects this list directly into the LLM prompt.
# =========================================================

from typing import Any, Dict, List
import json

COMPANY_RULES: List[Dict[str, Any]] = [
  {
    "rule_id": "FINANCIAL_001",
    "rule_no": "1",
    "rule_type": "FINANCIAL",
    "rule_description": "EXISTING LAPSED POLICIES",
    "condition_text": "Within 3 Years",
    "fields_to_validate": "1. National Identity Card Number2. Status of policy3. Date of Issuance",
    "rule_explanation": "System needs to check all the policies linked to a NIC number in core and if the status of these policies is not \"lapsed\"",
    "remarks_if_any": "WHAT ARE THE POLICY TO BE REVIVED",
    "comments": "Need to check with JN that what shoud be the stattus of lapsed policy.",
    "jicplc_comment": "Year parameter to be changed to 2 years",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_002",
    "rule_no": "2",
    "rule_type": "FINANCIAL",
    "rule_description": "EXISTING SURRENDERED POLICIES",
    "condition_text": "Less 1 YEAR",
    "fields_to_validate": "1. National Identity Card Number2. Status of policy3. Date of Issuance",
    "rule_explanation": "System needs to check all the policies linked to a NIC number and if the status of these policies is not \"surrendered\"",
    "remarks_if_any": "",
    "comments": "Need to check with JN that what shoud be the stattus of a surrendered policy.",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_003",
    "rule_no": "3",
    "rule_type": "FINANCIAL",
    "rule_description": "INSUFFICIENT MONTHLY INCOME",
    "condition_text": "120 TIMES MONTHLY INCOME AGAINST SUM NSURED",
    "fields_to_validate": "1. Monthly Income2. Sum Insured",
    "rule_explanation": "if120*Income < Sum Insured",
    "remarks_if_any": "is SI Exceeds 120 Time monthly Income then NSTP",
    "comments": "",
    "jicplc_comment": "SI willl include Basic, Additiona life, Criticall, FIB",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_004",
    "rule_no": "4",
    "rule_type": "FINANCIAL",
    "rule_description": "COMMISSION MANIPULATED QUOTATION",
    "condition_text": "If commission value is less or more than the standard commission (validate with commission set up)",
    "fields_to_validate": "1. Commision",
    "rule_explanation": "If commission value is changed by the branch user",
    "remarks_if_any": "",
    "comments": "Need to check if there is a field - commission, that can be modified by branch user",
    "jicplc_comment": "To be disabled",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_005",
    "rule_no": "5",
    "rule_type": "FINANCIAL",
    "rule_description": "MORE COVERS FOR MEMBERS THAN MAIN INSURED",
    "condition_text": "Validate with spouse cover",
    "fields_to_validate": "1. Life Assured (Main Life Assured)2. Life Assured (Spouse)3. Life Assured in all riders (main life Assured)4. Rider Life Assured (Spouse)",
    "rule_explanation": "Spouse should not have higher Lide assured or Rider benefits comaperd to the main assured.",
    "remarks_if_any": "",
    "comments": "Need to ask if we neeed to check for the children benefits or life assured too[Ankur] Yes We should check",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_006",
    "rule_no": "6",
    "rule_type": "FINANCIAL",
    "rule_description": "STANDING ORDER DETAILS ARE NOT AVAILABLE",
    "condition_text": "Standing order guideline",
    "fields_to_validate": "1. Bank2. Bank Code3. Branch4. Branch Code5. Account Number",
    "rule_explanation": "All the parameters in the standing order should be available in the proposal.",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "To be disabled",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_007",
    "rule_no": "7",
    "rule_type": "FINANCIAL",
    "rule_description": "MINIMUM CONTRIBUTION",
    "condition_text": "Validate with minimum contribution set-up in LI4.",
    "fields_to_validate": "1. Contribution",
    "rule_explanation": "Value of field 'Contribution' should be higher than the minimum set by JN",
    "remarks_if_any": "",
    "comments": "Need to check with JN regarding the value of minimum contribution",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_008",
    "rule_no": "8",
    "rule_type": "FINANCIAL",
    "rule_description": "REINSURANCE RATES ARE NOT AVAILABLE",
    "condition_text": "If rates are not entered",
    "fields_to_validate": "No on-screen field",
    "rule_explanation": "Rates will be stored in F-ins and will be fetched with a call as per inputs given on screen. In case the data is not available then this rule is to be triggered.",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_009",
    "rule_no": "9",
    "rule_type": "FINANCIAL",
    "rule_description": "FINANCIAL EVIDENCE ARE REQUIRED",
    "condition_text": "Validate with financial underwriting guidelines set up",
    "fields_to_validate": "",
    "rule_explanation": "If SI exceeds the defined amount then this check is triggered",
    "remarks_if_any": "If Si exceeds the defined amount then this check is triggred",
    "comments": "Rule to be shared by JN",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_010",
    "rule_no": "10",
    "rule_type": "FINANCIAL",
    "rule_description": "TOTAL LIFE COVER EXCEEDS AUTO UNDERWRITING LIMIT",
    "condition_text": "More than 15 MIL",
    "fields_to_validate": "1. Life Assured (Main Life Assured)2. Life Assured (Members)3. Life Assured in all riders (Main life Assured)4. Rider Life Assured (Members)",
    "rule_explanation": "Sum of basic cover and riders shouold be more than 15MN to trigger this rule",
    "remarks_if_any": "",
    "comments": "Need to check if we need to add the cover for riders too or only basic cover[Ankur] - Inclusive of Life , Additional Life + Critical Illness + FIB + Accident - this is per person, Considering all policies in force",
    "jicplc_comment": "Condition should be corrected as follows,without accident 15mil and with accident 20mil",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_011",
    "rule_no": "11",
    "rule_type": "FINANCIAL",
    "rule_description": "MONTHLY INCOME IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. Monthly Income",
    "rule_explanation": "Input field 'monthly income' is left blank/not available. This should be a field validation while saving the inputs",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_012",
    "rule_no": "12",
    "rule_type": "FINANCIAL",
    "rule_description": "FIB BENEFICIARY IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. Beneficiary Name",
    "rule_explanation": "Beneficiary details should be made mandatory such that it throws an error if the fields are left empty.",
    "remarks_if_any": "",
    "comments": "Need to add new fields for the beneficiary",
    "jicplc_comment": "This condition should be applied only for NSPS",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_013",
    "rule_no": "13",
    "rule_type": "FINANCIAL",
    "rule_description": "MAXIMUM PREMUM/CONTRIBUTION",
    "condition_text": "MCFP value of the \"Premium\" < 0r = 10% * Monthly Income",
    "fields_to_validate": "1. Beneficiary Name2. Monthly Income",
    "rule_explanation": "MCFP<=10%*Monthly Income",
    "remarks_if_any": "",
    "comments": "Need to add new fields for the beneficiary",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "MEDICAL_014",
    "rule_no": "14",
    "rule_type": "MEDICAL",
    "rule_description": "ADVERSE FAMILY HISTORY",
    "condition_text": "If any of the questions under family history is unhealthy, early death in the family/ deceased due to any ailment.",
    "fields_to_validate": "1. Check boxes for all medical questions",
    "rule_explanation": "If answer to any medical question is 'Yes', trigger this rule",
    "remarks_if_any": "",
    "comments": "Mnees to add Early Death Question",
    "jicplc_comment": "Condition to changed as follows, a) If both parents are unhealthy b) early death( before 60)",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_015",
    "rule_no": "15",
    "rule_type": "MEDICAL",
    "rule_description": "EXCESSIVE SMOKER",
    "condition_text": "21 sticks per week",
    "fields_to_validate": "1. Smoker2. Quantity per Week (displayed if the answer to smoke is 'Yes')",
    "rule_explanation": "If quantity per week > 21",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "MEDICAL_016",
    "rule_no": "16",
    "rule_type": "MEDICAL",
    "rule_description": "EXCESSIVE ALCOHOL CONSUMPTION - Hard",
    "condition_text": "1.5 Ltr Per month",
    "fields_to_validate": "1. Consume Alcohol2. Type3. Quantity per week",
    "rule_explanation": "If the type is 'Hard' then,if Quantity per week > 1.5 ltthe trigger this rule",
    "remarks_if_any": "",
    "comments": "Need to know if the check has to be on 'per week' quantity or 'per month' quantity",
    "jicplc_comment": "Condition should be corrected as per month",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "MEDICAL_017",
    "rule_no": "17",
    "rule_type": "MEDICAL",
    "rule_description": "EXCESSIVE ALCOHOL CONSUMPTION - Wine",
    "condition_text": "5 Bottles Per Month",
    "fields_to_validate": "1. Consume Alcohol2. Type3. Quantity per week",
    "rule_explanation": "If the type is 'Wine' then,if Quantity per week > 5 bottlesthe trigger this rule",
    "remarks_if_any": "",
    "comments": "Need to know if the check has to be on 'per week' quantity or 'per month' quantity",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "MEDICAL_018",
    "rule_no": "18",
    "rule_type": "MEDICAL",
    "rule_description": "EXCESSIVE ALCOHOL CONSUMPTION - Beer",
    "condition_text": "20 Bottles Per Month",
    "fields_to_validate": "1. Consume Alcohol2. Type3. Quantity per week",
    "rule_explanation": "If the type is 'Beer' then,if Quantity per week > 20 bottlesthe trigger this rule",
    "remarks_if_any": "",
    "comments": "Need to know if the check has to be on 'per week' quantity or 'per month' quantity",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "MEDICAL_019",
    "rule_no": "19",
    "rule_type": "MEDICAL",
    "rule_description": "GIVEN POSITIVE ANSWERS FOR QUESTION NO 6 ON FEMALE LIFE",
    "condition_text": "",
    "fields_to_validate": "Below 3 medical questions:1. Are you pregnant at the moment?2. Any abnormality of previous pregnancies or confinements?3. Have you had any disorder of the female organs (breast, ovaries, uterus)?",
    "rule_explanation": "If answer to any of the 3 questions is 'Yes'",
    "remarks_if_any": "",
    "comments": "Need to check if the list of questions is final ?",
    "jicplc_comment": "Condition should be changed as GIVEN POSITIVE ANSWERS FOR QUESTION NO 5,6 and 7 ON FEMALE LIFE",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_020",
    "rule_no": "20",
    "rule_type": "MEDICAL",
    "rule_description": "EXISTING INFORCE POLICIES",
    "condition_text": "TOTAL PREMIUM (INFORCE AND CURRENT PROPOSAL) 15% OF INSURED INCOME",
    "fields_to_validate": "1. National Identity Card Number2. Premium3. Monthly Income",
    "rule_explanation": "Total of monthly premiums for all the policies (existing proposal and existing policie) having same Life Insured should be less than 15% of monthly income",
    "remarks_if_any": "",
    "comments": "Need to check if the check is on the monthly income or yearly income",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_021",
    "rule_no": "21",
    "rule_type": "MEDICAL",
    "rule_description": "PREVIOUS CLAIM HISTORY",
    "condition_text": "If claims records are available for the life assured/ spouse / children",
    "fields_to_validate": "1. National Identity Card Number (for all members)2. Claims made in Past (Accordian)",
    "rule_explanation": "1. If previous claims are present in the proposal2. If claim history is present in the core for all the NIC's (main insured, life and spouse)",
    "remarks_if_any": "HISTORY TO BE POPULATED",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_022",
    "rule_no": "22",
    "rule_type": "MEDICAL",
    "rule_description": "BMI IS NOT WITHIN NORMAL RANGE",
    "condition_text": "18 - 25",
    "fields_to_validate": "1. BMI",
    "rule_explanation": "if 18 > BMI or BMI <25",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_023",
    "rule_no": "23",
    "rule_type": "MEDICAL",
    "rule_description": "MEDICALS SHOULD BE CALLED",
    "condition_text": "ANY",
    "fields_to_validate": "1. Check boxes for all medical questions",
    "rule_explanation": "If the medical question checked 'Yes' is associated to any medical report and that is pending in the uploaded document type",
    "remarks_if_any": "",
    "comments": "Need to know all the questions for which medical report is mandatory for underwriting",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_024",
    "rule_no": "24",
    "rule_type": "MEDICAL",
    "rule_description": "EXISTING UNAUTHORIZED PROPOSALS",
    "condition_text": "",
    "fields_to_validate": "1. National Identity Number2. Proposal Number3. Status",
    "rule_explanation": "If the NIC is linked to any proposals which are in the status 'On Hold' or 'Declined' or 'Discarded'. Need to search the core for this",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_025",
    "rule_no": "25",
    "rule_type": "MEDICAL",
    "rule_description": "EXISTING POLICIES WITH MEDICALS",
    "condition_text": "",
    "fields_to_validate": "1. National Identity Number2. Policy Number3. Sum Insured",
    "rule_explanation": "System needs to search the core system with NIC for all the policies issued in last 3 years. System should add up sum insured declared in all the policies for an individual and then apply the rule to have medical tests done.",
    "remarks_if_any": "",
    "comments": "Need to get the rules such that which medical tests are mandatory if the sum insured overshoots certain value",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_026",
    "rule_no": "26",
    "rule_type": "MEDICAL",
    "rule_description": "QUESTIONNAIRE HAS NOT BEEN ENTERED",
    "condition_text": "If answeres to any of the medical/non-medical or financial questionnaires are not completed",
    "fields_to_validate": "1. Check boxes for all the questionaries",
    "rule_explanation": "If any of the questionaire is not answered, the case should be treated as NSTP",
    "remarks_if_any": "",
    "comments": "Need to check if we can place a front end field validation such that the user is not allowed to proceed till the time all questions are answered",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_027",
    "rule_no": "27",
    "rule_type": "MEDICAL",
    "rule_description": "GIVEN POSITIVE ANSWERS FOR QUESTION NO.13",
    "condition_text": "To Additional Questionnaires",
    "fields_to_validate": "1. If any of the family member suffering from any ailment?",
    "rule_explanation": "If answer to this question is 'Yes' then the case has to be treated as NSTP",
    "remarks_if_any": "",
    "comments": "1. Need to add this question to the field list2. Need to confirm with JN that should we trigger thi rule in case this section is not empty or it should be triggered only if the answer to this question is 'Yes'",
    "jicplc_comment": "Condition should be changed as GIVEN POSITIVE ANSWERS FOR any of the SUB QUESTIONS under the additions additional questionaier",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_028",
    "rule_no": "28",
    "rule_type": "MEDICAL",
    "rule_description": "GIVEN POSITIVE ANSWERS FOR QUESTION NO.12",
    "condition_text": "To Medical Questionnaires",
    "fields_to_validate": "1. Life style accordian",
    "rule_explanation": "Will be triggered in case there are any inputs to the lifestyle section",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition should be changed as GIVEN POSITIVE ANSWERS FOR any of the SUB QUESTIONS no 2 onwards under medicals history for main life, spouse and children",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_029",
    "rule_no": "29",
    "rule_type": "MEDICAL",
    "rule_description": "WEIGHT IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. Weight",
    "rule_explanation": "If value for 'weight' is not ntered, the case should be treated as NSTP",
    "remarks_if_any": "",
    "comments": "Need to check if we can place a front end field validation such that the user is not allowed to proceed till the time inout is not give",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_030",
    "rule_no": "30",
    "rule_type": "MEDICAL",
    "rule_description": "HEIGHT IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. Height",
    "rule_explanation": "If value for 'height' is not ntered, the case should be treated as NSTP",
    "remarks_if_any": "",
    "comments": "Need to check if we can place a front end field validation such that the user is not allowed to proceed till the time inout is not give",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_031",
    "rule_no": "31",
    "rule_type": "MEDICAL",
    "rule_description": "CIGARETTE CONSUMPTION IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. Smoker2. Quantity per Week",
    "rule_explanation": "If the 'smoker' checkbox has been marked as 'Yes' but the 'quantity per week' is not entered",
    "remarks_if_any": "",
    "comments": "Need to check if we can place a front end field validation such that the user is not allowed to proceed till the time inout is not give",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "MEDICAL_032",
    "rule_no": "32",
    "rule_type": "MEDICAL",
    "rule_description": "ALCOHOL CONSUMPTION IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. Consume Alcohol2. Type3. Quantity per week",
    "rule_explanation": "If the 'Consume Alcohol' checkbox has been marked as 'Yes' but the 'quantity per week' is not entered",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "MEDICAL_033",
    "rule_no": "33",
    "rule_type": "MEDICAL",
    "rule_description": "TYPE OF ALCOHOL IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. Consume Alcohol2. Type",
    "rule_explanation": "If the 'Consume Alcohol' checkbox has been marked as 'Yes' but the 'type' is not entered",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "MEDICAL_034",
    "rule_no": "34",
    "rule_type": "MEDICAL",
    "rule_description": "VALIDATION OF TOTAL REIMBURSEMENT UNDER ALL POLICIES",
    "condition_text": "1 MIL",
    "fields_to_validate": "1. National Identity Number2. Sum Insured (Hospitalization - Reimbursement Rider)3. Status (Policy should be active)",
    "rule_explanation": "1. If Total of all Sum Insureds under Reimbursement Rider for all the active policies > 1 Million, system should trigger this rule2. Has to be checked for the main insured only",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Main life, spouse and all members should be considered",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_035",
    "rule_no": "35",
    "rule_type": "MEDICAL",
    "rule_description": "VALIDATION OF LIN TOTAL CASH PLAN UNDER ALL POLICIES",
    "condition_text": "Rs.10,000/-",
    "fields_to_validate": "1. National Identity Number2. Sum Insured (Hospitalization - Cash Plan Rider)3. Status (Policy should be active)",
    "rule_explanation": "1. If Total of all Sum Insureds under Cash Plan Rider for all the active policies > Rs 10,000, system should trigger this rule2. Has to be checked only for the main Insured",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is ok but it should be considered all members",
    "suggested_decision": "NSTP-MED",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_NON_MEDICAL_036",
    "rule_no": "36",
    "rule_type": "MEDICAL/NON-MEDICAL",
    "rule_description": "DECLINED INSURED",
    "condition_text": "If NIC / Name /Insured code is listed under Decline data base",
    "fields_to_validate": "1. National Identity Number2. Decline list (Database)",
    "rule_explanation": "Need to trigger this rule if the insured is listed under Decline list",
    "remarks_if_any": "",
    "comments": "1. Need to check if we can check with only the NIC number2. Need to confirm if this needs to be checked for the members too3. Need to confirm if the black list is same as the decline list",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED_OR_HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_NON_MEDICAL_037",
    "rule_no": "37",
    "rule_type": "MEDICAL/NON-MEDICAL",
    "rule_description": "AML INSURED",
    "condition_text": "If NIC / Name /Insured code is listed under Anti Money Laundering data base",
    "fields_to_validate": "1. National Identity Number2. Anti money laundering (Database)",
    "rule_explanation": "Need to trigger this rule if the insured is listed under anti money laundering list",
    "remarks_if_any": "",
    "comments": "1. Need to check if we can check with only the NIC number2. Need to confirm if this needs to be checked for the members too3. Need to confirm who will be maintaining and updating this list",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED_OR_HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "MEDICAL_NON_MEDICAL_038",
    "rule_no": "38",
    "rule_type": "MEDICAL/NON-MEDICAL",
    "rule_description": "ANY OTHER (USER WILL ADD THE DATABASES)",
    "condition_text": "If NIC / Name /Insured code is listed under any other data base introduced rom time to time",
    "fields_to_validate": "1. National Identity Number2. Any other list (Database)",
    "rule_explanation": "Need to trigger this rule if the insured is listed under any other list",
    "remarks_if_any": "",
    "comments": "1. Need to check if we can check with only the NIC number2. Need to confirm if this needs to be checked for the members too",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-MED_OR_HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_039",
    "rule_no": "39",
    "rule_type": "NON-MEDICAL",
    "rule_description": "EXCLUDED AGENT",
    "condition_text": "In active agent code",
    "fields_to_validate": "1. Agent Code2. Excluded Agent (Database)",
    "rule_explanation": "Need to trigger this rule if the insured is listed under Excluded Agent List",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_040",
    "rule_no": "40",
    "rule_type": "NON-MEDICAL",
    "rule_description": "AGE IS LESS THAN 18",
    "condition_text": "",
    "fields_to_validate": "1. Age",
    "rule_explanation": "Is Age <18 yrs, trigger this rule",
    "remarks_if_any": "",
    "comments": "1. Need to confirm if this needs to be checked for main insured or for all the members",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_041",
    "rule_no": "41",
    "rule_type": "NON-MEDICAL",
    "rule_description": "EXCLUDED PLAN",
    "condition_text": "In active agent plan",
    "fields_to_validate": "1. Plan",
    "rule_explanation": "If Plan is listed under the excluded plan list, trigger this",
    "remarks_if_any": "",
    "comments": "1. Need to check if we can put a screen validation and provent the user to proceed in case the plan is an excluded one",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_042",
    "rule_no": "42",
    "rule_type": "NON-MEDICAL",
    "rule_description": "HAZARDOUS OCCUPATION",
    "condition_text": "Validate with occupation classificaton",
    "fields_to_validate": "1. Occupation",
    "rule_explanation": "If occupation is listed under hazardous occupation",
    "remarks_if_any": "",
    "comments": "1. Need to add occupation code2. Need to confirm which class occupations are considered as hazardous",
    "jicplc_comment": "Not Required",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING, OCCUPATION_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_043",
    "rule_no": "43",
    "rule_type": "NON-MEDICAL",
    "rule_description": "OCCUPATION",
    "condition_text": "Validate with occupation classificaton",
    "fields_to_validate": "1. Occupation",
    "rule_explanation": "If occupation is listed under class 3 or 4",
    "remarks_if_any": "OTHER OCCUPATION IS IN CLASS 3 OR CLASS 4",
    "comments": "1. Need to check if this is same as the previous rule",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING, OCCUPATION_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_044",
    "rule_no": "44",
    "rule_type": "NON-MEDICAL",
    "rule_description": "UNREALIZED CHEQUE",
    "condition_text": "If unrealized cheque set up is ticked as yes.",
    "fields_to_validate": "1. Unrealized Check",
    "rule_explanation": "If Unrealized check is selected as 'Yes'",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_045",
    "rule_no": "45",
    "rule_type": "NON-MEDICAL",
    "rule_description": "ALERT-ONLY OBSERVATIONS AND NOTES",
    "condition_text": "If any observation field is commented",
    "fields_to_validate": "1. Alert-only observationa and remarks",
    "rule_explanation": "If remarks box is not empty",
    "remarks_if_any": "",
    "comments": "1. Need to input new fields in the form which should be remarks2. Need to confirm from JN that which user shall enter these remarks",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_046",
    "rule_no": "46",
    "rule_type": "NON-MEDICAL",
    "rule_description": "RESTRICTED OBSERVATIONS AND NOTES",
    "condition_text": "If any observation field is commented",
    "fields_to_validate": "1. Restricted observationa and remarks",
    "rule_explanation": "If remarks box is not empty",
    "remarks_if_any": "",
    "comments": "1. Need to input new fields in the form which should be remarks2. Need to confirm from JN that which user shall enter these remarks",
    "jicplc_comment": "To be disabled",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_047",
    "rule_no": "47",
    "rule_type": "NON-MEDICAL",
    "rule_description": "TPD MORTALITY RATES ARE NOT AVAILABLE",
    "condition_text": "If rates are not entered",
    "fields_to_validate": "No onscreen field",
    "rule_explanation": "If rate for the TPD mortality are not available in the system",
    "remarks_if_any": "",
    "comments": "1. Need to check with JN if we can place a fron end validation and should not allow the user to proceed",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_048",
    "rule_no": "48",
    "rule_type": "NON-MEDICAL",
    "rule_description": "INSURED AGE EXCEEDS 70 YEARS",
    "condition_text": "To be validated against age at entry",
    "fields_to_validate": "1. Age",
    "rule_explanation": "If Age > 70",
    "remarks_if_any": "",
    "comments": "1. Need to confirm if this needs to be checked for main insured or for all the members",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_049",
    "rule_no": "49",
    "rule_type": "NON-MEDICAL",
    "rule_description": "EXCLUSION OF POLICY FEE(LSP POLICIES)",
    "condition_text": "",
    "fields_to_validate": "1. Plan2. Policy fees (Database)",
    "rule_explanation": "If 'policy fees' has been applied, trigger this rule",
    "remarks_if_any": "",
    "comments": "Need to check with JN that how can a branch user apply policy fee in case the says that fees is not applied for LSP policies",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_050",
    "rule_no": "50",
    "rule_type": "NON-MEDICAL",
    "rule_description": "JOINT LIFE DETAILS ARE NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. Joint life details",
    "rule_explanation": "If the fields are empty",
    "remarks_if_any": "",
    "comments": "Joint life details section needs to be added",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_051",
    "rule_no": "51",
    "rule_type": "NON-MEDICAL",
    "rule_description": "NOMINEE IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. All fields under Nominee details accordian like Full Name, NIC etc",
    "rule_explanation": "If the fields are empty",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Conditon is valid only for NSPS",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_052",
    "rule_no": "52",
    "rule_type": "NON-MEDICAL",
    "rule_description": "PROPOSER'S DETAILS ARE NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. All fields under Proposer details accordian like Full Name, NIC etc",
    "rule_explanation": "If the fields are empty",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_053",
    "rule_no": "53",
    "rule_type": "NON-MEDICAL",
    "rule_description": "BENEFICIARY IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. All fields under Beneficiary details accordian like Full Name, NIC etc",
    "rule_explanation": "If the fields are empty",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "To be disabled until beneficiary field id developed",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_054",
    "rule_no": "54",
    "rule_type": "NON-MEDICAL",
    "rule_description": "NIC NUMBER IS INCORRECT/NOT AVAILABLE",
    "condition_text": "If NIC mismatches",
    "fields_to_validate": "1. NIC number",
    "rule_explanation": "If the fields are empty/incorrect",
    "remarks_if_any": "",
    "comments": "Need to check with JN if we can apply a front end field validation that will prevent the user from proceeding",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_055",
    "rule_no": "55",
    "rule_type": "NON-MEDICAL",
    "rule_description": "POLICY TERM IS LESS THAN 15(NGT01 PLAN)",
    "condition_text": "Validate with product configuration",
    "fields_to_validate": "1. Policy Term2. Plan",
    "rule_explanation": "If plan is NGT01 and policy term < 15",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "To be disabled",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_056",
    "rule_no": "56",
    "rule_type": "NON-MEDICAL",
    "rule_description": "INSURED'S MOBILE NO. IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. Mobile number (Main Insured)",
    "rule_explanation": "If the fields are empty",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_057",
    "rule_no": "57",
    "rule_type": "NON-MEDICAL",
    "rule_description": "PROPOSER'S MOBILE NO. IS NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. Mobile Number (Proposer)",
    "rule_explanation": "If the fields are empty",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_058",
    "rule_no": "58",
    "rule_type": "NON-MEDICAL",
    "rule_description": "INSURED'S PARTICULARS ARE NOT AVAILABLE",
    "condition_text": "If field is blank",
    "fields_to_validate": "1. All fields under the Main Insured",
    "rule_explanation": "If the fields are empty",
    "remarks_if_any": "",
    "comments": "Need to confirm with JN if this check needs to be placed on all fields or some particular fields",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_059",
    "rule_no": "59",
    "rule_type": "NON-MEDICAL",
    "rule_description": "REJECTED BY THE USER",
    "condition_text": "If user decides to reject auto underwriting",
    "fields_to_validate": "1. Auto underwriting",
    "rule_explanation": "If auto underwriting is rejected by user",
    "remarks_if_any": "",
    "comments": "Need to introduce this new field",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_060",
    "rule_no": "60",
    "rule_type": "NON-MEDICAL",
    "rule_description": "INSURED AGE EXCEEDS 70 YEARS(VSP PLAN)",
    "condition_text": "To be validated against age at entry",
    "fields_to_validate": "1. Age2. Plan",
    "rule_explanation": "If the plan is VSP and Insured age < 70",
    "remarks_if_any": "",
    "comments": "Need to confirm that if check needs to be placed on all insureds or the members too",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_061",
    "rule_no": "61",
    "rule_type": "NON-MEDICAL",
    "rule_description": "VALIDATION OF PROPOSER/INSURED AND AGENT CONTACT DETAILS",
    "condition_text": "If Proposer / Insured and Agent contact details are the same.",
    "fields_to_validate": "1. Mobile Number (Insured)2. Mobile number (Prpoposer)3. Mobile Number (Ageent's from the database maintained by core)",
    "rule_explanation": "If the Insured's or Proposer's mobile number is same to that of agent's, trigger this rule",
    "remarks_if_any": "",
    "comments": "Need to confirm if the check needs to be placed on all fields like address, home mobile number etc. or just a single check would be suffice",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_062",
    "rule_no": "62",
    "rule_type": "NON-MEDICAL",
    "rule_description": "VALIDATION OF PROPOSER/INSURED AND AGENT NIC NUMBERS",
    "condition_text": "If Proposer / Insured and Agent NIC numbers are the same.",
    "fields_to_validate": "1. NIC Number (Insured)2. NIC Number (Proposer)3. NIC Number (from agent's database in the core)",
    "rule_explanation": "If the insured's or proposer's NIC number matches to that of agent's, trigger this rule",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_063",
    "rule_no": "63",
    "rule_type": "NON-MEDICAL",
    "rule_description": "PROPOSER NIC NUMBER IS INCORRECT/NOT AVAILABLE",
    "condition_text": "NIC mismatch with Date of Birth",
    "fields_to_validate": "1 NIC number (proposer)",
    "rule_explanation": "1. If the NIC number field is left empty2. If the NIC number provided does not match to the DOB as maintained by the central repository",
    "remarks_if_any": "",
    "comments": "1. Need to confirm how do we match the NIC number to the DOB. Is it a front end validation or do we need to call any core database to get the details",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-DOC",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_064",
    "rule_no": "64",
    "rule_type": "NON-MEDICAL",
    "rule_description": "ADVISOR'S MOBILE NUMBER",
    "condition_text": "If Proposer / Insured and Agent mobile number are the same.",
    "fields_to_validate": "1. Mobile Number (Advisor)2. Mobile Number (Agent)",
    "rule_explanation": "If the advisor's and Agent's mobile numbers are same",
    "remarks_if_any": "",
    "comments": "1. Need to confirm the role of advisor in policy issuing2. Need to confirm if the check has to be done between agent and advisor or the Insured and advisor3. Need to introduce new fields for the advisor",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_065",
    "rule_no": "65",
    "rule_type": "NON-MEDICAL",
    "rule_description": "ADVISOR AS INSURED",
    "condition_text": "If Agent and Adviser are the same",
    "fields_to_validate": "1. NIC Number(Advisor)2. NIC Number (from agent database)",
    "rule_explanation": "If NIC numbers for advisor and the agent are same, trigger this rule",
    "remarks_if_any": "",
    "comments": "1. Need to confirm the role of advisor in policy issuing2. Need to introduce new fields for the advisor",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_066",
    "rule_no": "66",
    "rule_type": "NON-MEDICAL",
    "rule_description": "ACKNOWLEGMENET FOR AUTO AUTHORIZATION PROCESS",
    "condition_text": "User accepted auto underwriting",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_067",
    "rule_no": "67",
    "rule_type": "NON-MEDICAL",
    "rule_description": "RESIDENTIAL RISK",
    "condition_text": "If the country is not listed under “STANDARD COUNTRY LIST”",
    "fields_to_validate": "1. Country2. Standard country list (database)",
    "rule_explanation": "If country is not listed in standard country list, trigger this rule",
    "remarks_if_any": "",
    "comments": "1. Need to introduce the country field in all the address sections",
    "jicplc_comment": "Condition is correct",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "FINANCIAL_068",
    "rule_no": "68",
    "rule_type": "FINANCIAL",
    "rule_description": "ANNUAL PREMIUM EXCEEDED ANNUAL INCOME",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "FINANCIAL_069",
    "rule_no": "69",
    "rule_type": "FINANCIAL",
    "rule_description": "CASH MODE LIMIT EXCEEDED",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": ""
  },
  {
    "rule_id": "NON_MEDICAL_070",
    "rule_no": "70",
    "rule_type": "NON-MEDICAL",
    "rule_description": "OTHER NATIONALITY MAIN LIFE",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_071",
    "rule_no": "71",
    "rule_type": "NON-MEDICAL",
    "rule_description": "OTHER NATIONALITY SPOUSE",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_072",
    "rule_no": "72",
    "rule_type": "NON-MEDICAL",
    "rule_description": "OTHER NATIONALITY CHILD",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_073",
    "rule_no": "73",
    "rule_type": "NON-MEDICAL",
    "rule_description": "NON-RESIDENT MAIN LIFE",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_074",
    "rule_no": "74",
    "rule_type": "NON-MEDICAL",
    "rule_description": "NON-RESIDENT SPOUSE",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING, LIFESTYLE_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_075",
    "rule_no": "75",
    "rule_type": "NON-MEDICAL",
    "rule_description": "HIGH RISK OCCUPATION MAIN LIFE",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING, OCCUPATION_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_076",
    "rule_no": "76",
    "rule_type": "NON-MEDICAL",
    "rule_description": "HIGH RISK OCCUPATION SPOUSE",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING, OCCUPATION_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_077",
    "rule_no": "77",
    "rule_type": "NON-MEDICAL",
    "rule_description": "POLITICALLY EXPOSED MAIN LIFE",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  },
  {
    "rule_id": "NON_MEDICAL_078",
    "rule_no": "78",
    "rule_type": "NON-MEDICAL",
    "rule_description": "POLITICALLY EXPOSED SPOUSE",
    "condition_text": "",
    "fields_to_validate": "",
    "rule_explanation": "",
    "remarks_if_any": "",
    "comments": "",
    "jicplc_comment": "",
    "suggested_decision": "NSTP-HUMAN",
    "possible_loading_types": "HEALTH_LOADING"
  }
]


def get_company_rules_prompt() -> str:
    """
    Return all company rules as compact JSON text for prompt injection.
    """
    return json.dumps(COMPANY_RULES, indent=2, ensure_ascii=False)

def get_categorized_company_rules_prompt() -> str:
    """
    Returns the company rules broken down into logical parts:
    FINANCIAL, MEDICAL, and NON_MEDICAL. This explicitly prevents LLM hallucination
    by isolating rule-checking into distinct contextual blocks.
    """
    categorized = {
        "FINANCIAL": [],
        "MEDICAL": [],
        "NON_MEDICAL": []
    }
    
    for rule in COMPANY_RULES:
        rt = rule.get("rule_type", "").upper()
        if "FINANCIAL" in rt:
            categorized["FINANCIAL"].append(rule)
        elif "MEDICAL/NON-MEDICAL" in rt or "NON-MEDICAL" in rt or "NON_MEDICAL" in rt:
            categorized["NON_MEDICAL"].append(rule)
        elif "MEDICAL" in rt:
            categorized["MEDICAL"].append(rule)
        else:
            categorized["NON_MEDICAL"].append(rule)
            
    return json.dumps(categorized, indent=2, ensure_ascii=False)

def get_company_rules_count() -> int:
    return len(COMPANY_RULES)